# Generated by Django 4.0.4 on 2022-04-25 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_cart_quantity_cart_total_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Quantity',
            new_name='quantity',
        ),
    ]
