# Generated by Django 4.0.4 on 2022-06-07 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_userdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='zone',
        ),
        migrations.AddField(
            model_name='userdetails',
            name='area',
            field=models.CharField(default='main road', max_length=200),
        ),
    ]
