# Generated by Django 4.0.4 on 2022-06-07 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_userdetails_zone_userdetails_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='area',
            field=models.CharField(default='main road', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='district',
            field=models.CharField(default='Bhaktapur', max_length=200),
        ),
        migrations.AddField(
            model_name='order',
            name='province',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='order',
            name='town',
            field=models.CharField(default='Thimi', max_length=200),
        ),
    ]
