# Generated by Django 4.0.4 on 2022-06-07 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_order_state_alter_order_district_alter_order_town'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='state',
            new_name='status',
        ),
    ]
