# Generated by Django 4.0.4 on 2022-06-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='images/uwp540709.jpeg', upload_to='images/'),
        ),
    ]
